// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArrowLeftIcon: typeof import('./components/icons/ArrowLeftIcon.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    HomeHero: typeof import('./components/HomeHero.vue')['default']
    LangIcon: typeof import('./components/icons/LangIcon.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeDarkIcon: typeof import('./components/icons/ThemeDarkIcon.vue')['default']
    ThemeLightIcon: typeof import('./components/icons/ThemeLightIcon.vue')['default']
    ToggleDarkMode: typeof import('./components/ToggleDarkMode.vue')['default']
    ToggleLanguage: typeof import('./components/ToggleLanguage.vue')['default']
  }
}
